#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${HOME}/.local/share/smriti"
BIN_DIR="${HOME}/.local/bin"
APPLICATIONS_DIR="${HOME}/.local/share/applications"
ICON_THEME_DIR="${HOME}/.local/share/icons/hicolor"
BASHRC="${HOME}/.bashrc"
PATH_LINE='export PATH="$HOME/.local/bin:$PATH"'
PATH_MARKER="${INSTALL_DIR}/.path_modified"
AUTOGENERATED_DESKTOP_ENTRY="${APPLICATIONS_DIR}/smriti-local.desktop"

if [[ $# -gt 0 ]]; then
    if [[ $# -eq 1 && ( "$1" == --help || "$1" == -h ) ]]; then
        printf 'Usage: install.sh\nChecks dependencies and installs Smriti for the current user.\n'
        exit 0
    fi
    printf 'Unknown option: %s\n' "$1" >&2
    exit 1
fi

# Fail before creating files if the installed app could not run.
missing=()
for command in python3 ffmpeg ffplay pactl; do
    command -v "$command" >/dev/null 2>&1 || missing+=("$command")
done
if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import tkinter' >/dev/null 2>&1 || missing+=("Python tkinter")
    if ! python3 -c 'import gi; gi.require_version("Gtk", "3.0"); gi.require_version("AyatanaAppIndicator3", "0.1"); from gi.repository import Gtk, AyatanaAppIndicator3' >/dev/null 2>&1; then
        printf 'GTK/Ayatana AppIndicator is unavailable; Smriti will use its Tk window.\n'
        printf 'For the top-bar menu on Ubuntu/Debian: sudo apt install python3-gi gir1.2-ayatanaappindicator3-0.1\n'
    fi
fi
if [[ ${#missing[@]} -gt 0 ]]; then
    printf 'Missing dependency: %s\n' "${missing[@]}" >&2
    printf 'Ubuntu/Debian: sudo apt install python3 python3-tk ffmpeg pulseaudio-utils\n' >&2
    exit 1
fi

mkdir -p "${INSTALL_DIR}" "${INSTALL_DIR}/assets" "${INSTALL_DIR}/smriti_recorder" "${BIN_DIR}" "${APPLICATIONS_DIR}"
rm -f "${AUTOGENERATED_DESKTOP_ENTRY}"

install -m 755 "${SCRIPT_DIR}/recorder.py" "${INSTALL_DIR}/recorder.py"
install -m 755 "${SCRIPT_DIR}/smriti" "${INSTALL_DIR}/smriti"
install -m 755 "${SCRIPT_DIR}/uninstall.sh" "${INSTALL_DIR}/uninstall.sh"
install -m 644 "${SCRIPT_DIR}/smriti_recorder/"*.py "${INSTALL_DIR}/smriti_recorder/"
install -m 644 "${SCRIPT_DIR}/assets/"*.png "${INSTALL_DIR}/assets/"
ln -sfn "${INSTALL_DIR}/smriti" "${BIN_DIR}/smriti"
ln -sfn "${INSTALL_DIR}/uninstall.sh" "${BIN_DIR}/smriti-uninstall"

python3 - "${SCRIPT_DIR}/assets/smriti_logo.png" "${ICON_THEME_DIR}" <<'PY'
from pathlib import Path
import sys

try:
    from PIL import Image
except ImportError:
    Image = None

source = Path(sys.argv[1])
theme_dir = Path(sys.argv[2])

if Image is None:
    output_dir = theme_dir / "256x256" / "apps"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_dir.joinpath("smriti.png").write_bytes(source.read_bytes())
else:
    sizes = (32, 48, 64, 128, 256)
    with Image.open(source) as image:
        rgba = image.convert("RGBA")
        for size in sizes:
            output_dir = theme_dir / f"{size}x{size}" / "apps"
            output_dir.mkdir(parents=True, exist_ok=True)
            resized = rgba.resize((size, size), Image.Resampling.LANCZOS)
            resized.save(output_dir / "smriti.png")
PY

cat > "${APPLICATIONS_DIR}/smriti.desktop" <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=smriti
Comment=Small X11 desktop recorder
Exec="${BIN_DIR}/smriti"
Icon=smriti
StartupWMClass=smriti
X-GNOME-WMClass=smriti
Terminal=false
Categories=AudioVideo;Utility;
StartupNotify=false
EOF

if [[ ! -f "${BASHRC}" ]]; then
    touch "${BASHRC}"
fi

if ! grep -Fqx "${PATH_LINE}" "${BASHRC}"; then
    {
        printf "\n# Added by smriti installer\n"
        printf "%s\n" "${PATH_LINE}"
    } >> "${BASHRC}"
    touch "${PATH_MARKER}"
    PATH_UPDATED=1
else
    # Preserve ownership of the PATH block across repeated installations.
    PATH_UPDATED=0
fi

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "${APPLICATIONS_DIR}" >/dev/null 2>&1 || true
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -f -t "${ICON_THEME_DIR}" >/dev/null 2>&1 || true
fi

printf "Installed smriti.\n"
printf "Command: %s\n" "${BIN_DIR}/smriti"
printf "Uninstall: %s\n" "${BIN_DIR}/smriti-uninstall"
printf "Desktop entry: %s\n" "${APPLICATIONS_DIR}/smriti.desktop"

if [[ "${PATH_UPDATED}" -eq 1 ]]; then
    printf "Added ~/.local/bin to ~/.bashrc. Run 'source ~/.bashrc' or open a new shell.\n"
else
    printf "~/.local/bin was already on your PATH configuration.\n"
fi
