#!/usr/bin/env python3
"""GUI-first X11 screen recorder with optional webcam preview and microphone."""

from __future__ import annotations

import datetime as dt
import math
import os
import queue
import re
import shutil
import signal
import subprocess
import sys
import tempfile
import threading
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Callable

try:
    import tkinter as tk
except ImportError:  # pragma: no cover - depends on local system packages.
    tk = None

try:
    from PIL import Image
except ImportError:  # pragma: no cover - depends on local system packages.
    Image = None

SIZE_PATTERN = re.compile(r"^\d+x\d+$")
DESKTOP_ENTRY_RESERVED_CHARS = set(' \t\n"\'\\><~|&;$*?#()`')
APP_NAME = "smriti"
AUTOGENERATED_DESKTOP_ENTRY = "smriti-local.desktop"


def run_capture(command: list[str]) -> str | None:
    """Return stdout for a command, or None if unavailable or failing."""
    if shutil.which(command[0]) is None:
        return None
    try:
        proc = subprocess.run(
            command,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except subprocess.CalledProcessError:
        return None
    return proc.stdout.strip()


def detect_screen_size() -> str | None:
    """Best effort screen size detection for the active X11 display."""
    xrandr_output = run_capture(["xrandr", "--current"])
    if xrandr_output:
        for line in xrandr_output.splitlines():
            if "*" in line:
                token = line.split()[0]
                if SIZE_PATTERN.match(token):
                    return token

    xdpyinfo_output = run_capture(["xdpyinfo"])
    if xdpyinfo_output:
        match = re.search(r"dimensions:\s+(\d+x\d+)\s+pixels", xdpyinfo_output)
        if match:
            return match.group(1)

    return None


def get_pulse_sources() -> list[str]:
    output = run_capture(["pactl", "list", "short", "sources"])
    if not output:
        return []
    sources: list[str] = []
    for line in output.splitlines():
        parts = line.split()
        if len(parts) >= 2:
            sources.append(parts[1])
    return sources


def pick_default_mic_source(sources: list[str]) -> str | None:
    default = run_capture(["pactl", "get-default-source"])
    if default and not default.endswith(".monitor") and default in sources:
        return default

    for source in sources:
        if not source.endswith(".monitor"):
            return source

    return None


def pick_default_desktop_source(sources: list[str]) -> str | None:
    default_sink = run_capture(["pactl", "get-default-sink"])
    if default_sink:
        monitor = f"{default_sink}.monitor"
        if monitor in sources:
            return monitor

    for source in sources:
        if source.endswith(".monitor"):
            return source

    return None


def default_output_path() -> Path:
    timestamp = dt.datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
    return Path.home() / "Videos" / "smriti" / f"rec-{timestamp}.mp4"


def next_available_output_path() -> Path:
    base = default_output_path()
    if not base.exists():
        return base

    stem = base.stem
    suffix = base.suffix
    counter = 2
    while True:
        candidate = base.with_name(f"{stem}-{counter}{suffix}")
        if not candidate.exists():
            return candidate
        counter += 1


def has_playable_video_stream(path: Path) -> bool:
    if not path.exists() or path.stat().st_size == 0:
        return False
    if shutil.which("ffprobe") is None:
        return True
    proc = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=codec_type",
            "-of",
            "default=nokey=1:noprint_wrappers=1",
            str(path),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        check=False,
    )
    return proc.returncode == 0 and "video" in proc.stdout


def quote_concat_path(path: Path) -> str:
    return str(path).replace("'", r"'\''")


ASSET_FILENAMES = {
    "record": "record.png",
    "pause": "pause.png",
    "resume": "resume.png",
    "stop": "stop.png",
    "webcam_on": "cam.png",
    "webcam_off": "cam_off.png",
    "mic_on": "mic.png",
    "mic_off": "mic_off.png",
    "app_icon": "smriti_logo.png",
}


def asset_search_roots() -> tuple[Path, ...]:
    script_dir = Path(__file__).resolve().parent
    return (script_dir / "assets", script_dir)


def find_asset_path(filename: str) -> Path | None:
    for root in asset_search_roots():
        candidate = root / filename
        if candidate.exists():
            return candidate
    return None


def find_app_icon_path() -> Path | None:
    return find_asset_path(ASSET_FILENAMES["app_icon"])


def find_app_class_name() -> str:
    override = os.environ.get("SMRITI_WM_CLASS", "").strip()
    if override:
        return override
    return APP_NAME


def desktop_applications_dir() -> Path:
    xdg_data_home = os.environ.get("XDG_DATA_HOME", "").strip()
    if xdg_data_home:
        return Path(xdg_data_home).expanduser() / "applications"
    return Path.home() / ".local" / "share" / "applications"


def desktop_entry_path(entry_name: str) -> Path:
    return desktop_applications_dir() / entry_name


def desktop_entry_exists(entry_name: str) -> bool:
    search_paths = [desktop_applications_dir()]
    xdg_data_dirs = os.environ.get("XDG_DATA_DIRS", "").strip()
    if xdg_data_dirs:
        search_paths.extend(Path(path).expanduser() / "applications" for path in xdg_data_dirs.split(":") if path)
    else:
        search_paths.extend(Path(path) / "applications" for path in ("/usr/local/share", "/usr/share"))
    return any((directory / entry_name).exists() for directory in search_paths)


def escape_desktop_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace("\r", "\\r")
    )


def quote_desktop_exec_arg(argument: str) -> str:
    escaped = escape_desktop_string(argument).replace('"', '\\"').replace("`", "\\`").replace("$", "\\$")
    escaped = escaped.replace("%", "%%")
    if any(character in DESKTOP_ENTRY_RESERVED_CHARS for character in argument):
        return f'"{escaped}"'
    return escaped


def desktop_exec_command(script_path: Path) -> str:
    wrapper_path = script_path.with_name(APP_NAME)
    if wrapper_path.exists() and os.access(wrapper_path, os.X_OK):
        return quote_desktop_exec_arg(str(wrapper_path))
    return " ".join(
        quote_desktop_exec_arg(part)
        for part in (sys.executable, str(script_path))
    )


def build_autogenerated_desktop_entry(script_path: Path, icon_path: Path) -> str:
    script_dir = script_path.parent
    return "\n".join(
        (
            "[Desktop Entry]",
            "Version=1.0",
            "Type=Application",
            f"Name={APP_NAME}",
            "Comment=Small X11 desktop recorder",
            f"Exec={desktop_exec_command(script_path)}",
            f"Path={escape_desktop_string(str(script_dir))}",
            f"Icon={escape_desktop_string(str(icon_path))}",
            f"StartupWMClass={escape_desktop_string(find_app_class_name())}",
            "Terminal=false",
            "NoDisplay=true",
            "StartupNotify=false",
            "",
        )
    )


def ensure_runtime_desktop_entry() -> None:
    icon_path = find_app_icon_path()
    if icon_path is None:
        return

    # Recent Linux docks often match X11 windows to desktop entries by WM_CLASS.
    # Installed runs already have that metadata; repo runs need a hidden entry.
    generated_entry = desktop_entry_path(AUTOGENERATED_DESKTOP_ENTRY)
    if desktop_entry_exists(f"{APP_NAME}.desktop"):
        if generated_entry.exists():
            try:
                generated_entry.unlink()
            except OSError:
                pass
        return

    script_path = Path(__file__).resolve()
    entry_text = build_autogenerated_desktop_entry(script_path, icon_path)
    applications_dir = generated_entry.parent
    try:
        applications_dir.mkdir(parents=True, exist_ok=True)
        current_text = generated_entry.read_text(encoding="utf-8") if generated_entry.exists() else None
        if current_text == entry_text:
            return
        generated_entry.write_text(entry_text, encoding="utf-8")
    except OSError:
        return

    if shutil.which("update-desktop-database") is not None:
        subprocess.run(
            ["update-desktop-database", str(applications_dir)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )


def detect_icon_content_box(icon_path: Path, width: int, height: int) -> tuple[int, int, int, int]:
    if Image is None:
        return (0, 0, width, height)

    try:
        with Image.open(icon_path) as image:
            alpha_box = image.convert("RGBA").getchannel("A").getbbox()
    except Exception:
        return (0, 0, width, height)

    if alpha_box is None:
        return (0, 0, width, height)

    left, top, right, bottom = alpha_box
    content_width = right - left
    content_height = bottom - top
    square_size = max(content_width, content_height)

    center_x = left + content_width / 2
    center_y = top + content_height / 2

    square_left = max(0, math.floor(center_x - square_size / 2))
    square_top = max(0, math.floor(center_y - square_size / 2))
    square_right = min(width, square_left + square_size)
    square_bottom = min(height, square_top + square_size)

    square_left = max(0, square_right - square_size)
    square_top = max(0, square_bottom - square_size)

    return (square_left, square_top, square_right, square_bottom)


UI_THEME = {
    "window_bg": "#0b0f14",
    "panel_bg": "#131922",
    "panel_alt": "#1a222d",
    "control_panel_bg": "#f5f5f5",
    "control_panel_outline": "#d2d9e2",
    "control_text": "#202833",
    "control_text_muted": "#8d98a6",
    "outline": "#283343",
    "outline_soft": "#202a36",
    "text_primary": "#f3efe8",
    "text_secondary": "#a5b1c2",
    "text_muted": "#6f7b8b",
    "accent_record": "#ff7a59",
    "accent_pause": "#d3b06e",
    "accent_stop": "#f19082",
    "accent_toggle": "#74c4a0",
    "accent_idle": "#7d8ca3",
}


def clamp(value: float, lower: float, upper: float) -> float:
    return max(lower, min(upper, value))


def blend(color_a: str, color_b: str, factor: float) -> str:
    factor = clamp(factor, 0.0, 1.0)
    a = color_a.lstrip("#")
    b = color_b.lstrip("#")
    channels = [
        round(int(a[index : index + 2], 16) + (int(b[index : index + 2], 16) - int(a[index : index + 2], 16)) * factor)
        for index in (0, 2, 4)
    ]
    return "#" + "".join(f"{channel:02x}" for channel in channels)


def draw_rounded_rectangle(
    canvas: tk.Canvas,
    x1: float,
    y1: float,
    x2: float,
    y2: float,
    radius: float,
    *,
    fill: str,
    outline: str,
    width: int = 1,
) -> int:
    radius = clamp(radius, 0, min((x2 - x1) / 2, (y2 - y1) / 2))
    points = [
        x1 + radius,
        y1,
        x1 + radius,
        y1,
        x2 - radius,
        y1,
        x2 - radius,
        y1,
        x2,
        y1,
        x2,
        y1 + radius,
        x2,
        y1 + radius,
        x2,
        y2 - radius,
        x2,
        y2 - radius,
        x2,
        y2,
        x2 - radius,
        y2,
        x2 - radius,
        y2,
        x1 + radius,
        y2,
        x1 + radius,
        y2,
        x1,
        y2,
        x1,
        y2 - radius,
        x1,
        y2 - radius,
        x1,
        y1 + radius,
        x1,
        y1 + radius,
        x1,
        y1,
    ]
    return canvas.create_polygon(
        points,
        smooth=True,
        splinesteps=32,
        fill=fill,
        outline=outline,
        width=width,
    )


class StatusBadge(tk.Frame):
    def __init__(self, master: tk.Misc, *, width: int, height: int, background: str) -> None:
        super().__init__(master, bg=background)
        self._width = width
        self._height = height
        self._text = ""
        self._fill = UI_THEME["panel_alt"]
        self._outline = UI_THEME["outline"]
        self._text_color = UI_THEME["text_secondary"]
        self._dot = UI_THEME["accent_idle"]
        self.canvas = tk.Canvas(
            self,
            width=width,
            height=height,
            bg=background,
            bd=0,
            highlightthickness=0,
        )
        self.canvas.pack()
        self.render()

    def set_badge(self, *, text: str, fill: str, outline: str, text_color: str, dot: str) -> None:
        self._text = text
        self._fill = fill
        self._outline = outline
        self._text_color = text_color
        self._dot = dot
        self.render()

    def render(self) -> None:
        self.canvas.delete("all")
        draw_rounded_rectangle(
            self.canvas,
            1,
            1,
            self._width - 1,
            self._height - 1,
            14,
            fill=self._fill,
            outline=self._outline,
        )
        self.canvas.create_oval(14, 11, 20, 17, fill=self._dot, outline="")
        self.canvas.create_text(
            self._width / 2 + 8,
            self._height / 2,
            text=self._text,
            font=("TkDefaultFont", 9, "bold"),
            fill=self._text_color,
        )


class IconControl(tk.Frame):
    def __init__(
        self,
        master: tk.Misc,
        *,
        label: str,
        icon_kind: str,
        command: Callable[[], None] | None,
        accent: str,
        background: str,
        variant: str = "toggle",
        width: int,
        height: int,
    ) -> None:
        super().__init__(master, bg=background)
        self.command = command
        self.accent = accent
        self.background = background
        self.variant = variant
        self.width = width
        self.height = height
        self.label = label
        self.icon_kind = icon_kind
        self.icon_images: dict[tuple[str, int], tk.PhotoImage | None] = {}
        self.enabled = True
        self.active = False
        self.hovered = False
        self.pressed = False
        self.canvas = tk.Canvas(
            self,
            width=width,
            height=height,
            bg=background,
            bd=0,
            highlightthickness=0,
        )
        self.canvas.pack()
        self._bind_events()
        self.render()

    def _bind_events(self) -> None:
        for sequence, handler in (
            ("<Enter>", self._on_enter),
            ("<Leave>", self._on_leave),
            ("<ButtonPress-1>", self._on_press),
            ("<ButtonRelease-1>", self._on_release),
        ):
            self.canvas.bind(sequence, handler)

    def _on_enter(self, _event: tk.Event[tk.Misc]) -> None:
        self.hovered = True
        self.render()

    def _on_leave(self, _event: tk.Event[tk.Misc]) -> None:
        self.hovered = False
        self.pressed = False
        self.render()

    def _on_press(self, _event: tk.Event[tk.Misc]) -> None:
        if not self.enabled or self.command is None:
            return
        self.pressed = True
        self.render()

    def _on_release(self, event: tk.Event[tk.Misc]) -> None:
        should_fire = (
            self.enabled
            and self.command is not None
            and self.pressed
            and 0 <= event.x <= self.width
            and 0 <= event.y <= self.height
        )
        self.pressed = False
        self.render()
        if should_fire:
            self.command()

    def set_visual_state(
        self,
        *,
        label: str | None = None,
        icon_kind: str | None = None,
        enabled: bool | None = None,
        active: bool | None = None,
    ) -> None:
        if label is not None:
            self.label = label
        if icon_kind is not None:
            self.icon_kind = icon_kind
        if enabled is not None:
            self.enabled = enabled
        if active is not None:
            self.active = active
        self.render()

    def _palette(self) -> tuple[str, str, str, str]:
        if self.variant == "transport":
            fill = self.accent
            outline = blend(self.accent, "#000000", 0.18)
            icon_color = UI_THEME["control_text"]
            label_color = UI_THEME["control_text"]

            if self.hovered and self.enabled:
                fill = blend(fill, "#ffffff", 0.06)
            if self.pressed and self.enabled:
                fill = blend(fill, "#000000", 0.10)
            if not self.enabled:
                fill = blend(fill, self.background, 0.40)
                outline = blend(outline, self.background, 0.34)
                icon_color = UI_THEME["control_text_muted"]
                label_color = UI_THEME["control_text_muted"]

            return fill, outline, icon_color, label_color

        fill = self.background
        outline = UI_THEME["control_panel_outline"]
        icon_color = UI_THEME["control_text"]
        label_color = UI_THEME["control_text"]

        if self.active:
            outline = blend(outline, self.accent, 0.48)
            icon_color = self.accent
            label_color = self.accent
        elif self.hovered and self.enabled:
            outline = blend(outline, UI_THEME["control_text"], 0.18)

        if not self.enabled:
            outline = blend(outline, self.background, 0.36)
            icon_color = UI_THEME["control_text_muted"]
            label_color = UI_THEME["control_text_muted"]
        elif self.pressed:
            outline = blend(outline, "#000000", 0.12)

        return fill, outline, icon_color, label_color

    def _draw_record_icon(self, cx: float, cy: float, size: float, color: str) -> None:
        radius = size * 0.28
        if self.active:
            ring = size * 0.52
            self.canvas.create_oval(
                cx - ring,
                cy - ring,
                cx + ring,
                cy + ring,
                outline=blend(self.accent, UI_THEME["panel_bg"], 0.20),
                width=2,
            )
        self.canvas.create_oval(cx - radius, cy - radius, cx + radius, cy + radius, fill=color, outline="")

    def _draw_play_icon(self, cx: float, cy: float, size: float, color: str) -> None:
        half = size * 0.42
        self.canvas.create_polygon(
            cx - half * 0.5,
            cy - half,
            cx + half,
            cy,
            cx - half * 0.5,
            cy + half,
            fill=color,
            outline="",
        )

    def _draw_pause_icon(self, cx: float, cy: float, size: float, color: str) -> None:
        bar_width = size * 0.18
        gap = size * 0.14
        bar_height = size * 0.50
        self.canvas.create_rectangle(
            cx - gap - bar_width,
            cy - bar_height,
            cx - gap,
            cy + bar_height,
            fill=color,
            outline="",
        )
        self.canvas.create_rectangle(
            cx + gap,
            cy - bar_height,
            cx + gap + bar_width,
            cy + bar_height,
            fill=color,
            outline="",
        )

    def _draw_stop_icon(self, cx: float, cy: float, size: float, color: str) -> None:
        half = size * 0.35
        self.canvas.create_rectangle(cx - half, cy - half, cx + half, cy + half, fill=color, outline="")

    def _draw_webcam_icon(self, cx: float, cy: float, size: float, color: str) -> None:
        body_width = size * 0.98
        body_height = size * 0.54
        x1 = cx - body_width / 2
        y1 = cy - body_height / 2 + 2
        x2 = cx + body_width / 2
        y2 = cy + body_height / 2 + 2
        draw_rounded_rectangle(
            self.canvas,
            x1,
            y1,
            x2,
            y2,
            size * 0.14,
            fill="",
            outline=color,
            width=2,
        )
        tab_height = size * 0.16
        self.canvas.create_rectangle(
            x1 + size * 0.18,
            y1 - tab_height,
            x1 + size * 0.52,
            y1 + size * 0.02,
            fill=color,
            outline=color,
        )
        lens_radius = size * 0.22
        self.canvas.create_oval(
            cx - lens_radius,
            cy - lens_radius + 2,
            cx + lens_radius,
            cy + lens_radius + 2,
            outline=color,
            width=2,
        )
        self.canvas.create_oval(cx - 2, cy, cx + 2, cy + 4, fill=color, outline="")

    def _draw_mic_icon(self, cx: float, cy: float, size: float, color: str) -> None:
        head_width = size * 0.24
        head_height = size * 0.38
        draw_rounded_rectangle(
            self.canvas,
            cx - head_width,
            cy - head_height - 4,
            cx + head_width,
            cy + head_height * 0.18 - 4,
            head_width,
            fill=color,
            outline=color,
        )
        self.canvas.create_line(
            cx,
            cy + head_height * 0.18 - 4,
            cx,
            cy + size * 0.42,
            fill=color,
            width=2,
            capstyle=tk.ROUND,
        )
        self.canvas.create_arc(
            cx - size * 0.42,
            cy - size * 0.14,
            cx + size * 0.42,
            cy + size * 0.56,
            start=200,
            extent=140,
            style=tk.ARC,
            outline=color,
            width=2,
        )
        self.canvas.create_line(
            cx - size * 0.28,
            cy + size * 0.48,
            cx + size * 0.28,
            cy + size * 0.48,
            fill=color,
            width=2,
            capstyle=tk.ROUND,
        )

    def _asset_icon_name(self) -> str | None:
        if self.icon_kind == "record":
            return ASSET_FILENAMES["record"]
        if self.icon_kind == "pause":
            return ASSET_FILENAMES["pause"]
        if self.icon_kind == "resume":
            return ASSET_FILENAMES["resume"]
        if self.icon_kind == "stop":
            return ASSET_FILENAMES["stop"]
        if self.icon_kind == "webcam":
            return ASSET_FILENAMES["webcam_on"] if self.active else ASSET_FILENAMES["webcam_off"]
        if self.icon_kind == "mic":
            return ASSET_FILENAMES["mic_on"] if self.active else ASSET_FILENAMES["mic_off"]
        return None

    def _load_asset_icon(self, filename: str, size: int) -> tk.PhotoImage | None:
        cache_key = (filename, size)
        if cache_key in self.icon_images:
            return self.icon_images[cache_key]

        icon_path = find_asset_path(filename)
        if icon_path is None:
            self.icon_images[cache_key] = None
            return None

        try:
            source = tk.PhotoImage(file=str(icon_path), master=self)
            width = source.width()
            height = source.height()
            content_box = detect_icon_content_box(icon_path, width, height)
            cropped = source
            if content_box != (0, 0, width, height):
                cropped = tk.PhotoImage(master=self)
                cropped.tk.call(
                    str(cropped),
                    "copy",
                    str(source),
                    "-from",
                    content_box[0],
                    content_box[1],
                    content_box[2],
                    content_box[3],
                    "-shrink",
                )

            source_size = max(1, cropped.width(), cropped.height())
            if source_size == size:
                image = cropped
            else:
                divisor = math.gcd(source_size, size)
                zoom = max(1, size // divisor)
                subsample = max(1, source_size // divisor)
                image = cropped.zoom(zoom, zoom)
                if subsample > 1:
                    image = image.subsample(subsample, subsample)

            self.icon_images[cache_key] = image
            return image
        except tk.TclError:
            self.icon_images[cache_key] = None
            return None

    def _draw_icon(self, cx: float, cy: float, size: float, color: str) -> None:
        asset_icon_name = self._asset_icon_name()
        if asset_icon_name is not None:
            asset_icon = self._load_asset_icon(asset_icon_name, round(size))
            if asset_icon is not None:
                self.canvas.create_image(cx, cy, image=asset_icon)
                return

        if self.icon_kind == "record":
            self._draw_record_icon(cx, cy, size, color)
        elif self.icon_kind == "play":
            self._draw_play_icon(cx, cy, size, color)
        elif self.icon_kind == "pause":
            self._draw_pause_icon(cx, cy, size, color)
        elif self.icon_kind in {"play", "resume"}:
            self._draw_play_icon(cx, cy, size, color)
        elif self.icon_kind == "stop":
            self._draw_stop_icon(cx, cy, size, color)
        elif self.icon_kind == "webcam":
            self._draw_webcam_icon(cx, cy, size, color)
        elif self.icon_kind == "mic":
            self._draw_mic_icon(cx, cy, size, color)

    def render(self) -> None:
        fill, outline, icon_color, label_color = self._palette()
        self.canvas.delete("all")
        radius = 22 if self.variant == "transport" else 18
        draw_rounded_rectangle(
            self.canvas,
            1,
            1,
            self.width - 1,
            self.height - 1,
            radius,
            fill=fill,
            outline=outline,
        )

        icon_only = not self.label
        icon_y = self.height / 2 if icon_only else (26 if self.variant == "transport" else 25)
        if icon_only:
            icon_size = 34 if self.variant == "transport" else 30
        else:
            icon_size = 30 if self.variant == "transport" else 28
        self._draw_icon(self.width / 2, icon_y, icon_size, icon_color)
        if self.label:
            self.canvas.create_text(
                self.width / 2,
                self.height - 18,
                text=self.label,
                font=("TkDefaultFont", 9, "bold"),
                fill=label_color,
            )

        cursor = "hand2" if self.enabled and self.command is not None else "arrow"
        self.canvas.configure(cursor=cursor)


def read_pipe(pipe: object) -> str:
    if pipe is None:
        return ""
    try:
        return pipe.read().strip()
    except ValueError:
        return ""


def summarize_error(prefix: str, stderr_output: str) -> str:
    lines = [line.strip() for line in stderr_output.splitlines() if line.strip()]
    if not lines:
        return prefix
    return f"{prefix} {lines[-1]}"


@dataclass
class AppConfig:
    display: str = field(default_factory=lambda: os.environ.get("DISPLAY", ":0.0"))
    fps: int = 30
    webcam_device: str = "/dev/video0"
    webcam_width: int = 320
    webcam_window_x: int = 20
    webcam_window_y: int = 20
    webcam_always_on_top: bool = True


@dataclass
class ControllerState:
    mode: str = "idle"
    status: str = "Ready."
    busy: bool = False
    webcam_enabled: bool = False
    webcam_preview_running: bool = False
    mic_enabled: bool = False
    mic_available: bool = False
    desktop_audio_available: bool = False
    webcam_available: bool = False
    ffmpeg_available: bool = False
    ffplay_available: bool = False
    current_output: str = ""
    last_output: str = ""


@dataclass
class RecordingSession:
    final_output: Path
    temp_dir: Path
    segments: list[Path] = field(default_factory=list)


@dataclass
class ActiveSegment:
    path: Path
    process: subprocess.Popen[str]


class WebcamWindowController:
    """Controls the live webcam preview window."""

    def __init__(self, config: AppConfig) -> None:
        self.config = config
        self.process: subprocess.Popen[str] | None = None
        self.title = "smriti - webcam"

    def _build_command(self) -> list[str]:
        command = [
            "ffplay",
            "-hide_banner",
            "-loglevel",
            "error",
            "-fflags",
            "nobuffer",
            "-flags",
            "low_delay",
            "-an",
            "-window_title",
            self.title,
            "-left",
            str(self.config.webcam_window_x),
            "-top",
            str(self.config.webcam_window_y),
            "-vf",
            f"scale={self.config.webcam_width}:-1",
            "-f",
            "v4l2",
            "-framerate",
            str(self.config.fps),
            "-i",
            self.config.webcam_device,
        ]
        if self.config.webcam_always_on_top:
            command.insert(1, "-alwaysontop")
        return command

    def _launch(self) -> subprocess.Popen[str]:
        return subprocess.Popen(
            self._build_command(),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            text=True,
        )

    def start(self) -> None:
        webcam_path = Path(self.config.webcam_device)
        if not webcam_path.exists():
            raise RuntimeError(f"Webcam device does not exist: {self.config.webcam_device}")
        if shutil.which("ffplay") is None:
            raise RuntimeError("ffplay is not installed or not in PATH.")

        self.process = self._launch()
        time.sleep(0.8)
        if self.process.poll() is not None:
            stderr_output = read_pipe(self.process.stderr)
            self.process = None
            raise RuntimeError(summarize_error("Failed to start webcam preview.", stderr_output))

    def ensure_running(self) -> bool:
        if not self.process:
            return False
        if self.process.poll() is None:
            return True

        if self.process.stderr:
            self.process.stderr.close()
        self.process = None
        return False

    def stop(self) -> None:
        if not self.process:
            return
        if self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=3)
            except subprocess.TimeoutExpired:
                self.process.kill()
                self.process.wait(timeout=2)
        if self.process.stderr:
            self.process.stderr.close()
        self.process = None


def resolve_audio_sources(mic_enabled: bool) -> tuple[str | None, str | None, list[str]]:
    sources = get_pulse_sources()
    warnings: list[str] = []

    desktop_source = pick_default_desktop_source(sources)
    if not desktop_source:
        warnings.append("Desktop audio unavailable; recording silence instead.")

    mic_source = None
    if mic_enabled:
        mic_source = pick_default_mic_source(sources)
        if not mic_source:
            warnings.append("Microphone unavailable; continuing without mic.")

    return desktop_source, mic_source, warnings


def build_segment_command(
    config: AppConfig,
    output_path: Path,
    mic_enabled: bool,
) -> tuple[list[str], list[str]]:
    command: list[str] = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-y",
        "-nostdin",
        "-thread_queue_size",
        "1024",
        "-f",
        "x11grab",
        "-framerate",
        str(config.fps),
    ]

    screen_size = detect_screen_size()
    if screen_size:
        command.extend(["-video_size", screen_size])

    command.extend(["-i", f"{config.display}+0,0"])

    desktop_source, mic_source, warnings = resolve_audio_sources(mic_enabled)

    input_index = 1
    desktop_index: int | None = None
    if desktop_source:
        command.extend(["-thread_queue_size", "1024", "-f", "pulse", "-i", desktop_source])
        desktop_index = input_index
        input_index += 1

    mic_index: int | None = None
    if mic_source:
        command.extend(["-thread_queue_size", "1024", "-f", "pulse", "-i", mic_source])
        mic_index = input_index
        input_index += 1

    command.extend(["-f", "lavfi", "-i", "anullsrc=channel_layout=stereo:sample_rate=48000"])
    silence_index = input_index

    audio_inputs: list[str] = []
    if desktop_index is not None:
        audio_inputs.append(f"[{desktop_index}:a]")
    if mic_index is not None:
        audio_inputs.append(f"[{mic_index}:a]")
    audio_inputs.append(f"[{silence_index}:a]")

    if len(audio_inputs) == 1:
        audio_filter = (
            f"{audio_inputs[0]}aformat=sample_fmts=fltp:sample_rates=48000:"
            "channel_layouts=stereo[aout]"
        )
    else:
        audio_filter = (
            "".join(audio_inputs)
            + f"amix=inputs={len(audio_inputs)}:duration=longest:dropout_transition=0,"
            "aresample=async=1:first_pts=0,"
            "aformat=sample_fmts=fltp:sample_rates=48000:channel_layouts=stereo[aout]"
        )

    command.extend(
        [
            "-filter_complex",
            audio_filter,
            "-map",
            "0:v",
            "-map",
            "[aout]",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "23",
            "-pix_fmt",
            "yuv420p",
            "-r",
            str(config.fps),
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-ac",
            "2",
            "-ar",
            "48000",
            str(output_path),
        ]
    )

    return command, warnings


class RecorderController:
    """Serializes recorder operations off the UI thread."""

    def __init__(self, config: AppConfig) -> None:
        self.config = config
        self.state = ControllerState(status="Checking environment...")
        self.events: queue.Queue[dict[str, object]] = queue.Queue()
        self.commands: queue.Queue[tuple[str, object | None]] = queue.Queue()
        self.webcam_controller = WebcamWindowController(config)
        self.session: RecordingSession | None = None
        self.active_segment: ActiveSegment | None = None
        self.stop_requested = False
        self._refresh_capabilities()
        self._publish_state()
        self.thread = threading.Thread(target=self._run_loop, daemon=True)
        self.thread.start()

    def _refresh_capabilities(self) -> None:
        pulse_sources = get_pulse_sources()
        self.state.ffmpeg_available = shutil.which("ffmpeg") is not None
        self.state.ffplay_available = shutil.which("ffplay") is not None
        self.state.webcam_available = Path(self.config.webcam_device).exists()
        self.state.mic_available = pick_default_mic_source(pulse_sources) is not None
        self.state.desktop_audio_available = pick_default_desktop_source(pulse_sources) is not None

        if not self.state.ffmpeg_available:
            self.state.status = "ffmpeg is required but not installed or not in PATH."
        elif not self.config.display:
            self.state.status = "DISPLAY is not set."
        elif self.state.status == "Checking environment...":
            self.state.status = "Ready."

    def _publish_state(self) -> None:
        if self.state.webcam_enabled:
            self.state.webcam_preview_running = self.webcam_controller.ensure_running()
        else:
            self.state.webcam_preview_running = False
        self.events.put({"type": "state", "state": asdict(self.state)})

    def send(self, name: str, payload: object | None = None) -> None:
        self.commands.put((name, payload))

    def _run_loop(self) -> None:
        while not self.stop_requested:
            try:
                name, payload = self.commands.get(timeout=0.25)
            except queue.Empty:
                self._poll_background_processes()
                continue

            try:
                if name == "toggle_webcam":
                    self._handle_toggle_webcam(bool(payload))
                elif name == "toggle_mic":
                    self._handle_toggle_mic(bool(payload))
                elif name == "start":
                    self._handle_start()
                elif name == "pause":
                    self._handle_pause()
                elif name == "stop":
                    self._handle_stop()
                elif name == "shutdown":
                    self._handle_shutdown()
                else:
                    self.state.status = f"Unknown command: {name}"
            except Exception as err:  # pragma: no cover - defensive UI safety.
                self.state.busy = False
                self.state.status = str(err)
            finally:
                self._refresh_capabilities()
                self._publish_state()

    def _poll_background_processes(self) -> None:
        state_changed = False
        preview_running = False
        if self.state.webcam_enabled:
            preview_running = self.webcam_controller.ensure_running()
            if not preview_running and self.state.webcam_enabled:
                self.state.webcam_enabled = False
                self.state.status = "Webcam preview disabled."
                state_changed = True
        if self.state.webcam_preview_running != preview_running:
            self.state.webcam_preview_running = preview_running
            state_changed = True

        if self.active_segment and self.active_segment.process.poll() is not None:
            kept, message = self._collect_finished_segment()
            self.active_segment = None
            if self.session and self.session.segments:
                self.state.mode = "paused"
                self.state.status = message or "Recording stopped unexpectedly. Press Start to resume."
            else:
                self.state.mode = "idle"
                self.state.current_output = ""
                self.state.status = message or "Recording stopped unexpectedly."
                self._clear_session_files(keep_segments=kept)
                self.session = None
            state_changed = True

        if state_changed:
            self._publish_state()

    def _handle_toggle_webcam(self, enabled: bool) -> None:
        self.state.busy = True
        self._refresh_capabilities()
        if enabled:
            if not self.state.ffplay_available:
                self.state.webcam_enabled = False
                self.state.status = "ffplay is required for the webcam preview."
                self.state.busy = False
                return
            if not self.state.webcam_available:
                self.state.webcam_enabled = False
                self.state.status = f"Webcam device not found: {self.config.webcam_device}"
                self.state.busy = False
                return
            self.webcam_controller.start()
            self.state.webcam_enabled = True
            self.state.status = "Webcam preview enabled."
        else:
            self.webcam_controller.stop()
            self.state.webcam_enabled = False
            self.state.status = "Webcam preview disabled."
        self.state.busy = False

    def _handle_toggle_mic(self, enabled: bool) -> None:
        self.state.busy = True
        self._refresh_capabilities()
        if enabled and not self.state.mic_available:
            self.state.mic_enabled = False
            self.state.status = "No microphone source is available right now."
            self.state.busy = False
            return

        if self.state.mic_enabled == enabled:
            self.state.busy = False
            return

        self.state.mic_enabled = enabled
        if self.state.mode == "recording":
            self.state.status = "Applying microphone change..."
            self._rotate_segment()
            if self.state.mode == "recording":
                state_text = "enabled" if enabled else "disabled"
                self.state.status = f"Microphone {state_text}."
        else:
            state_text = "enabled" if enabled else "disabled"
            self.state.status = f"Microphone {state_text}."
        self.state.busy = False

    def _handle_start(self) -> None:
        if not self.state.ffmpeg_available:
            self.state.status = "ffmpeg is required but not installed or not in PATH."
            return

        self.state.busy = True
        self._refresh_capabilities()
        if self.state.mode == "recording":
            self.state.busy = False
            return

        if self.session is None:
            final_output = next_available_output_path()
            final_output.parent.mkdir(parents=True, exist_ok=True)
            temp_dir = Path(tempfile.mkdtemp(prefix="smriti-", dir="/tmp"))
            self.session = RecordingSession(final_output=final_output, temp_dir=temp_dir)
            self.state.current_output = str(final_output)

        self._start_segment()
        self.state.mode = "recording"
        self.state.busy = False

    def _handle_pause(self) -> None:
        if self.state.mode != "recording":
            return

        self.state.busy = True
        self.state.status = "Pausing recording..."
        self._stop_current_segment()
        self.state.mode = "paused"
        self.state.status = "Paused."
        self.state.busy = False

    def _handle_stop(self) -> None:
        if self.session is None and self.active_segment is None:
            self.state.mode = "idle"
            self.state.status = "Ready."
            return

        self.state.busy = True
        self.state.status = "Finalizing recording..."
        saved_path: Path | None = None
        try:
            if self.state.mode == "recording":
                self._stop_current_segment()
            saved_path = self._finalize_session()
        finally:
            self.state.mode = "idle"
            self.state.current_output = ""
            self.state.busy = False

        self.state.last_output = str(saved_path) if saved_path else self.state.last_output
        if saved_path:
            self.state.status = f"Saved recording: {saved_path}"
        else:
            self.state.status = "Nothing was saved."

    def _handle_shutdown(self) -> None:
        self.state.busy = True
        try:
            if self.state.mode == "recording":
                self._stop_current_segment()
            if self.session is not None:
                saved_path = self._finalize_session()
                if saved_path:
                    self.state.last_output = str(saved_path)
        finally:
            self.webcam_controller.stop()
            self.state.webcam_enabled = False
            self.state.mode = "idle"
            self.state.current_output = ""
            self.state.busy = False
            self.stop_requested = True

    def _start_segment(self) -> None:
        assert self.session is not None

        segment_path = self.session.temp_dir / f"segment-{len(self.session.segments) + 1:04d}.mp4"
        command, warnings = build_segment_command(
            config=self.config,
            output_path=segment_path,
            mic_enabled=self.state.mic_enabled,
        )
        process = subprocess.Popen(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            text=True,
        )
        time.sleep(0.8)
        if process.poll() is not None:
            stderr_output = read_pipe(process.stderr)
            raise RuntimeError(summarize_error("Failed to start recording.", stderr_output))

        self.active_segment = ActiveSegment(path=segment_path, process=process)
        if warnings:
            self.state.status = " ".join(warnings)
        else:
            self.state.status = "Recording..."

    def _rotate_segment(self) -> None:
        self._stop_current_segment()
        if self.session is None:
            return
        self.state.mode = "paused"
        self._start_segment()
        self.state.mode = "recording"

    def _stop_current_segment(self) -> None:
        if not self.active_segment:
            return

        process = self.active_segment.process
        if process.poll() is None:
            process.send_signal(signal.SIGINT)
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                process.terminate()
                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=3)

        kept, message = self._collect_finished_segment()
        self.active_segment = None
        if message:
            self.state.status = message
        if not kept and self.session and not self.session.segments:
            self.state.status = "The latest segment could not be finalized."

    def _collect_finished_segment(self) -> tuple[bool, str | None]:
        if not self.active_segment or self.session is None:
            return False, None

        segment_path = self.active_segment.path
        process = self.active_segment.process
        stderr_output = read_pipe(process.stderr)
        if process.stderr:
            process.stderr.close()

        playable = has_playable_video_stream(segment_path)
        if playable:
            self.session.segments.append(segment_path)
            if process.returncode not in (0, 130, 255, -2):
                return True, summarize_error(
                    "Recorder exited with a warning; kept the segment.",
                    stderr_output,
                )
            return True, None

        if segment_path.exists():
            return False, summarize_error("Discarded an incomplete segment.", stderr_output)
        return False, summarize_error("Recorder stopped without producing a playable segment.", stderr_output)

    def _finalize_session(self) -> Path | None:
        if self.session is None:
            return None

        success = False
        result: Path | None = None
        temp_dir = self.session.temp_dir
        try:
            if not self.session.segments:
                self._clear_session_files(keep_segments=False)
                return None

            self.session.final_output.parent.mkdir(parents=True, exist_ok=True)
            if len(self.session.segments) == 1:
                shutil.move(str(self.session.segments[0]), str(self.session.final_output))
                result = self.session.final_output
                success = True
                return result

            concat_list = self.session.temp_dir / "segments.txt"
            concat_lines = [
                f"file '{quote_concat_path(segment)}'" for segment in self.session.segments
            ]
            concat_list.write_text("\n".join(concat_lines) + "\n", encoding="utf-8")

            merged_copy = self.session.temp_dir / "merged-copy.mp4"
            copy_proc = subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-loglevel",
                    "error",
                    "-y",
                    "-f",
                    "concat",
                    "-safe",
                    "0",
                    "-i",
                    str(concat_list),
                    "-c",
                    "copy",
                    "-movflags",
                    "+faststart",
                    str(merged_copy),
                ],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                text=True,
                check=False,
            )
            if copy_proc.returncode == 0 and has_playable_video_stream(merged_copy):
                shutil.move(str(merged_copy), str(self.session.final_output))
                result = self.session.final_output
                success = True
                return result

            merged_reencode = self.session.temp_dir / "merged-reencode.mp4"
            reencode_proc = subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-loglevel",
                    "error",
                    "-y",
                    "-f",
                    "concat",
                    "-safe",
                    "0",
                    "-i",
                    str(concat_list),
                    "-c:v",
                    "libx264",
                    "-preset",
                    "veryfast",
                    "-crf",
                    "23",
                    "-pix_fmt",
                    "yuv420p",
                    "-c:a",
                    "aac",
                    "-b:a",
                    "160k",
                    "-ac",
                    "2",
                    "-ar",
                    "48000",
                    "-movflags",
                    "+faststart",
                    str(merged_reencode),
                ],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                text=True,
                check=False,
            )
            if reencode_proc.returncode == 0 and has_playable_video_stream(merged_reencode):
                shutil.move(str(merged_reencode), str(self.session.final_output))
                result = self.session.final_output
                success = True
                return result

            copy_error = summarize_error("Merge failed.", copy_proc.stderr or "")
            reencode_error = summarize_error("Fallback merge failed.", reencode_proc.stderr or "")
            raise RuntimeError(f"{copy_error} {reencode_error}".strip())
        except Exception as err:
            self.session = None
            raise RuntimeError(f"{err} Segment files were kept in {temp_dir}.") from err
        finally:
            if success:
                self._clear_session_files(keep_segments=False)

        return result

    def _clear_session_files(self, keep_segments: bool) -> None:
        if self.session is None:
            return

        temp_dir = self.session.temp_dir
        if keep_segments:
            return
        if temp_dir.exists():
            shutil.rmtree(temp_dir, ignore_errors=True)
        self.session = None


class RecorderApp:
    POLL_INTERVAL_MS = 150

    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.icon_source_image: tk.PhotoImage | None = None
        self.icon_images: list[tk.PhotoImage] = []
        self.root.title("smriti")
        self.root.resizable(False, False)
        self.root.protocol("WM_DELETE_WINDOW", self.on_close)
        self._set_window_icon()

        self.closing = False
        self.state: ControllerState | None = None
        self.controller = RecorderController(AppConfig())

        self._build_ui()
        self._poll_events()

    def _set_window_icon(self) -> None:
        icon_path = find_app_icon_path()
        if icon_path is None:
            return
        try:
            self.icon_source_image = tk.PhotoImage(file=str(icon_path), master=self.root)
            source = self.icon_source_image
            width = source.width()
            height = source.height()
            content_box = detect_icon_content_box(icon_path, width, height)
            content_width = content_box[2] - content_box[0]
            content_height = content_box[3] - content_box[1]

            # X11 stores Tk icons in _NET_WM_ICON. Sending the full source image
            # can exceed server request limits when the asset is very large.
            # Tk recommends providing a small set of icon sizes, with the larger
            # one first, so window managers can pick an appropriate variant.
            variants: list[tk.PhotoImage] = []
            for target_size in (128, 32):
                x_scale = max(1, math.ceil(content_width / target_size))
                y_scale = max(1, math.ceil(content_height / target_size))
                variant = tk.PhotoImage(master=self.root)
                variant.tk.call(
                    str(variant),
                    "copy",
                    str(source),
                    "-from",
                    content_box[0],
                    content_box[1],
                    content_box[2],
                    content_box[3],
                    "-shrink",
                    "-subsample",
                    x_scale,
                    y_scale,
                )
                if any(
                    existing.width() == variant.width() and existing.height() == variant.height()
                    for existing in variants
                ):
                    continue
                variants.append(variant)

            if not variants:
                variants = [source]

            self.icon_images = variants
            self.root.iconphoto(True, *self.icon_images)
        except tk.TclError:
            self.icon_source_image = None
            self.icon_images = []

    def _build_ui(self) -> None:
        theme = UI_THEME
        self.root.configure(bg=theme["window_bg"])

        self.shell = tk.Frame(self.root, bg=theme["window_bg"], padx=14, pady=14)
        self.shell.pack(fill="both", expand=True)

        self.panel = tk.Frame(
            self.shell,
            bg=theme["panel_bg"],
            padx=14,
            pady=14,
            highlightthickness=1,
            highlightbackground=theme["outline"],
        )
        self.panel.pack(fill="both", expand=True)

        self.controls_card = tk.Frame(
            self.panel,
            bg=theme["control_panel_bg"],
            padx=12,
            pady=12,
            highlightthickness=1,
            highlightbackground=theme["control_panel_outline"],
        )
        self.controls_card.pack(fill="x")

        self.controls_row = tk.Frame(self.controls_card, bg=theme["control_panel_bg"])
        self.controls_row.pack()

        self.webcam_button = IconControl(
            self.controls_row,
            label="",
            icon_kind="webcam",
            command=self.on_toggle_webcam,
            accent=theme["accent_toggle"],
            background=theme["control_panel_bg"],
            variant="toggle",
            width=78,
            height=72,
        )
        self.webcam_button.pack(side="left", padx=(0, 8))

        self.mic_button = IconControl(
            self.controls_row,
            label="",
            icon_kind="mic",
            command=self.on_toggle_mic,
            accent=theme["accent_toggle"],
            background=theme["control_panel_bg"],
            variant="toggle",
            width=78,
            height=72,
        )
        self.mic_button.pack(side="left", padx=(0, 12))

        self.controls_divider = tk.Frame(
            self.controls_row,
            width=1,
            height=44,
            bg=theme["control_panel_outline"],
        )
        self.controls_divider.pack(side="left", padx=(0, 12), pady=14)

        self.start_button = IconControl(
            self.controls_row,
            label="",
            icon_kind="record",
            command=self.on_primary_action,
            accent=theme["accent_record"],
            background=theme["control_panel_bg"],
            variant="transport",
            width=84,
            height=72,
        )
        self.start_button.pack(side="left")

        self.output_label = tk.Label(
            self.panel,
            text="",
            anchor="w",
            justify="left",
            font=("TkFixedFont", 9),
            bg=theme["panel_bg"],
            fg=theme["text_secondary"],
            wraplength=420,
        )
        self.output_visible = False

    def on_toggle_webcam(self) -> None:
        if not self.state or self.state.busy:
            return
        self.controller.send("toggle_webcam", not self.state.webcam_enabled)

    def on_toggle_mic(self) -> None:
        if not self.state or self.state.busy:
            return
        self.controller.send("toggle_mic", not self.state.mic_enabled)

    def on_start(self) -> None:
        if not self.state or self.state.busy:
            return
        self.controller.send("start")

    def on_primary_action(self) -> None:
        if not self.state or self.state.busy:
            return
        if self.state.mode in {"recording", "paused"}:
            self.controller.send("stop")
            return
        self.controller.send("start")

    def on_pause(self) -> None:
        if not self.state or self.state.busy:
            return
        self.controller.send("pause")

    def on_stop(self) -> None:
        if not self.state or self.state.busy:
            return
        self.controller.send("stop")

    def on_close(self) -> None:
        if self.closing:
            return
        self.closing = True
        self.start_button.set_visual_state(enabled=False)
        self.webcam_button.set_visual_state(enabled=False)
        self.mic_button.set_visual_state(enabled=False)
        self.controller.send("shutdown")
        self._wait_for_shutdown()

    def _wait_for_shutdown(self) -> None:
        if self.controller.thread.is_alive():
            self.root.after(self.POLL_INTERVAL_MS, self._wait_for_shutdown)
            return
        self.root.destroy()

    def _poll_events(self) -> None:
        while True:
            try:
                event = self.controller.events.get_nowait()
            except queue.Empty:
                break
            if event.get("type") == "state":
                self._apply_state(event["state"])
        self.root.after(self.POLL_INTERVAL_MS, self._poll_events)

    def _apply_state(self, raw_state: object) -> None:
        assert isinstance(raw_state, dict)
        self.state = ControllerState(**raw_state)

        state = self.state

        controls_disabled = state.busy or self.closing
        can_record = state.ffmpeg_available and not controls_disabled

        self.start_button.set_visual_state(
            label="",
            icon_kind="stop" if state.mode in {"recording", "paused"} else "record",
            enabled=(not controls_disabled and state.mode in {"recording", "paused"}) or can_record,
            active=False,
        )
        self.webcam_button.set_visual_state(
            label="",
            icon_kind="webcam",
            active=state.webcam_enabled,
            enabled=not controls_disabled,
        )
        self.mic_button.set_visual_state(
            label="",
            icon_kind="mic",
            active=state.mic_enabled,
            enabled=not controls_disabled,
        )

        output_path = state.last_output if state.mode == "idle" and state.last_output else ""
        if output_path:
            self.output_label.configure(text=output_path)
            if not self.output_visible:
                self.output_label.pack(fill="x", pady=(10, 0))
                self.output_visible = True
        elif self.output_visible:
            self.output_label.pack_forget()
            self.output_visible = False


def launch_gui() -> int:
    if tk is None:
        print("tkinter is required to run the smriti GUI.", file=os.sys.stderr)
        return 1

    ensure_runtime_desktop_entry()
    app_class_name = find_app_class_name()
    root = tk.Tk(baseName=app_class_name, className=app_class_name)
    app = RecorderApp(root)
    root.mainloop()
    return 0


def main() -> int:
    return launch_gui()


if __name__ == "__main__":
    raise SystemExit(main())
