from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

APP_NAME = "smriti"
AUTOGENERATED_DESKTOP_ENTRY = "smriti-local.desktop"


@dataclass
class AppConfig:
    display: str = field(default_factory=lambda: os.environ.get("DISPLAY", ":0.0"))
    fps: int = 30
    webcam_device: str = "/dev/video0"
    webcam_width: int = 320
    webcam_flip_horizontal: bool = True
    webcam_window_x: int = 20
    webcam_window_y: int = 20
    webcam_always_on_top: bool = True
    default_webcam_enabled: bool = True
    default_mic_enabled: bool = True


@dataclass
class ControllerState:
    mode: str = "idle"
    status: str = "Ready."
    busy: bool = False
    webcam_enabled: bool = False
    webcam_flipped: bool = False
    webcam_preview_running: bool = False
    mic_enabled: bool = False
    mic_available: bool = False
    desktop_audio_available: bool = False
    webcam_available: bool = False
    ffmpeg_available: bool = False
    ffplay_available: bool = False
    current_output: str = ""
    last_output: str = ""


@dataclass
class RecordingSession:
    final_output: Path
    temp_dir: Path
    segments: list[Path] = field(default_factory=list)


@dataclass
class ActiveSegment:
    path: Path
    process: subprocess.Popen[str]
