from __future__ import annotations

import math
import os
import shutil
import subprocess
import sys
from pathlib import Path

from .config import APP_NAME, AUTOGENERATED_DESKTOP_ENTRY

try:
    from PIL import Image
except ImportError:  # pragma: no cover - depends on local system packages.
    Image = None

DESKTOP_ENTRY_RESERVED_CHARS = set(' \t\n"\'\\><~|&;$*?#()`')
ASSET_FILENAMES = {
    "record": "record.png",
    "pause": "pause.png",
    "resume": "resume.png",
    "stop": "stop.png",
    "webcam_on": "cam.png",
    "webcam_off": "cam_off.png",
    "mic_on": "mic.png",
    "mic_off": "mic_off.png",
    "app_icon": "smriti_logo.png",
}


def app_root() -> Path:
    return Path(__file__).resolve().parent.parent


def entry_script_path() -> Path:
    return app_root() / "recorder.py"


def asset_search_roots() -> tuple[Path, ...]:
    root = app_root()
    return (root / "assets", root)


def find_asset_path(filename: str) -> Path | None:
    for root in asset_search_roots():
        candidate = root / filename
        if candidate.exists():
            return candidate
    return None


def find_app_icon_path() -> Path | None:
    return find_asset_path(ASSET_FILENAMES["app_icon"])


def find_app_class_name() -> str:
    override = os.environ.get("SMRITI_WM_CLASS", "").strip()
    if override:
        return override
    return APP_NAME


def desktop_applications_dir() -> Path:
    xdg_data_home = os.environ.get("XDG_DATA_HOME", "").strip()
    if xdg_data_home:
        return Path(xdg_data_home).expanduser() / "applications"
    return Path.home() / ".local" / "share" / "applications"


def desktop_entry_path(entry_name: str) -> Path:
    return desktop_applications_dir() / entry_name


def desktop_entry_exists(entry_name: str) -> bool:
    search_paths = [desktop_applications_dir()]
    xdg_data_dirs = os.environ.get("XDG_DATA_DIRS", "").strip()
    if xdg_data_dirs:
        search_paths.extend(Path(path).expanduser() / "applications" for path in xdg_data_dirs.split(":") if path)
    else:
        search_paths.extend(Path(path) / "applications" for path in ("/usr/local/share", "/usr/share"))
    return any((directory / entry_name).exists() for directory in search_paths)


def escape_desktop_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace("\r", "\\r")
    )


def quote_desktop_exec_arg(argument: str) -> str:
    escaped = escape_desktop_string(argument).replace('"', '\\"').replace("`", "\\`").replace("$", "\\$")
    escaped = escaped.replace("%", "%%")
    if any(character in DESKTOP_ENTRY_RESERVED_CHARS for character in argument):
        return f'"{escaped}"'
    return escaped


def desktop_exec_command(script_path: Path) -> str:
    wrapper_path = script_path.with_name(APP_NAME)
    if wrapper_path.exists() and os.access(wrapper_path, os.X_OK):
        return quote_desktop_exec_arg(str(wrapper_path))
    return " ".join(
        quote_desktop_exec_arg(part)
        for part in (sys.executable, str(script_path))
    )


def build_autogenerated_desktop_entry(script_path: Path, icon_path: Path) -> str:
    script_dir = script_path.parent
    return "\n".join(
        (
            "[Desktop Entry]",
            "Version=1.0",
            "Type=Application",
            f"Name={APP_NAME}",
            "Comment=Small X11 desktop recorder",
            f"Exec={desktop_exec_command(script_path)}",
            f"Path={escape_desktop_string(str(script_dir))}",
            f"Icon={escape_desktop_string(str(icon_path))}",
            f"StartupWMClass={escape_desktop_string(find_app_class_name())}",
            "Terminal=false",
            "NoDisplay=true",
            "StartupNotify=false",
            "",
        )
    )


def ensure_runtime_desktop_entry() -> None:
    icon_path = find_app_icon_path()
    if icon_path is None:
        return

    # Recent Linux docks often match X11 windows to desktop entries by WM_CLASS.
    # Installed runs already have that metadata; repo runs need a hidden entry.
    generated_entry = desktop_entry_path(AUTOGENERATED_DESKTOP_ENTRY)
    if desktop_entry_exists(f"{APP_NAME}.desktop"):
        if generated_entry.exists():
            try:
                generated_entry.unlink()
            except OSError:
                pass
        return

    script_path = entry_script_path()
    entry_text = build_autogenerated_desktop_entry(script_path, icon_path)
    applications_dir = generated_entry.parent
    try:
        applications_dir.mkdir(parents=True, exist_ok=True)
        current_text = generated_entry.read_text(encoding="utf-8") if generated_entry.exists() else None
        if current_text == entry_text:
            return
        generated_entry.write_text(entry_text, encoding="utf-8")
    except OSError:
        return

    if shutil.which("update-desktop-database") is not None:
        subprocess.run(
            ["update-desktop-database", str(applications_dir)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )


def detect_icon_content_box(icon_path: Path, width: int, height: int) -> tuple[int, int, int, int]:
    if Image is None:
        return (0, 0, width, height)

    try:
        with Image.open(icon_path) as image:
            alpha_box = image.convert("RGBA").getchannel("A").getbbox()
    except Exception:
        return (0, 0, width, height)

    if alpha_box is None:
        return (0, 0, width, height)

    left, top, right, bottom = alpha_box
    content_width = right - left
    content_height = bottom - top
    square_size = max(content_width, content_height)

    center_x = left + content_width / 2
    center_y = top + content_height / 2

    square_left = max(0, math.floor(center_x - square_size / 2))
    square_top = max(0, math.floor(center_y - square_size / 2))
    square_right = min(width, square_left + square_size)
    square_bottom = min(height, square_top + square_size)

    square_left = max(0, square_right - square_size)
    square_top = max(0, square_bottom - square_size)

    return (square_left, square_top, square_right, square_bottom)
